name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js and pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Approve build scripts
        run: pnpm config set enable-pre-post-scripts true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Approve build scripts
        run: pnpm approve-builds -g

      - name: Build application
        run: pnpm build